export const database = [
    {
      codigoProduto: 1,
      tituloProduto: "Bolsa Bege Elegante",
      preco: 50000.00,
      descricao: "Bolsa Bege Elegante",
      imagemProduto: {
        img1: "./images/bolsa_1.png",
        img2: "./images/bolsa_1.png",
        img3: "./images/bolsa_1.png",
        img4: "./images/bolsa_1.png",
      },
      categoriaProduto: "Bolsas",
      classificacaoProduto: "Mais_Vendidos",
      exibirHome: true,
    },
    {
      codigoProduto: 2,
      tituloProduto: "Bolsa Verde Elegante",
      preco: 50000.00,
      descricao: "Bolsa Verde Elegante",
      imagemProduto: {
        img1: "./images/bolsa_2.png",
        img2: "./images/bolsa_2.png",
        img3: "./images/bolsa_2.png",
        img4: "./images/bolsa_2.png",
      },
      categoriaProduto: "Bolsas",
      classificacaoProduto: "Mais_Vendidos",
      exibirHome: true,
    },
    {
      codigoProduto: 3,
      tituloProduto: "Bolsa Vermelha Elegante",
      preco: 50000.00,
      descricao: "Bolsa Vermelha Elegante",
      imagemProduto: {
        img1: "./images/bolsa_3.png",
        img2: "./images/bolsa_3.png",
        img3: "./images/bolsa_3.png",
        img4: "./images/bolsa_3.png",
      },
      categoriaProduto: "Bolsas",
      classificacaoProduto: "Mais_Vendidos",
      exibirHome: true,
    },
    {
      codigoProduto: 4,
      tituloProduto: "Bolsa Preta Elegante",
      preco: 50000.00,
      descricao: "Bolsa Preta Elegante",
      imagemProduto: {
        img1: "./images/bolsa_4.png",
        img2: "./images/bolsa_4.png",
        img3: "./images/bolsa_4.png",
        img4: "./images/bolsa_4.png",
      },
      categoriaProduto: "Bolsas",
      classificacaoProduto: "Mais_Vendidos",
      exibirHome: true,
    },
    {
      codigoProduto: 5,
      tituloProduto: "Bolsa Bege Elegante",
      preco: 50000.00,
      descricao: "Bolsa Bege Elegante",
      imagemProduto: {
        img1: "./images/bolsa_5.png",
        img2: "./images/bolsa_5.png",
        img3: "./images/bolsa_5.png",
        img4: "./images/bolsa_5.png",
      },
      categoriaProduto: "Bolsas",
      classificacaoProduto: "Mais_Vendidos2",
      exibirHome: true,
    },
    {
      codigoProduto: 6,
      tituloProduto: "Bolsa Verde Elegante",
      preco: 50000.00,
      descricao: "Bolsa Verde Elegante",
      imagemProduto: {
        img1: "./images/bolsa_6.png",
        img2: "./images/bolsa_6.png",
        img3: "./images/bolsa_6.png",
        img4: "./images/bolsa_6.png",
      },
      categoriaProduto: "Bolsas",
      classificacaoProduto: "Mais_Vendidos2",
      exibirHome: true,
    },
    {
      codigoProduto: 7,
      tituloProduto: "Bolsa Vermelha Elegante",
      preco: 50000.00,
      descricao: "Bolsa Vermelha Elegante",
      imagemProduto: {
        img1: "./images/bolsa_7.png",
        img2: "./images/bolsa_7.png",
        img3: "./images/bolsa_7.png",
        img4: "./images/bolsa_7.png",
      },
      categoriaProduto: "Bolsas",
      classificacaoProduto: "Mais_Vendidos2",
      exibirHome: true,
    },
    {
      codigoProduto: 8,
      tituloProduto: "Bolsa Preta Elegante",
      preco: 50000.00,
      descricao: "Bolsa Preta Elegante",
      imagemProduto: {
        img1: "./images/bolsa_8.png",
        img2: "./images/bolsa_8.png",
        img3: "./images/bolsa_8.png",
        img4: "./images/bolsa_8.png",
      },
      categoriaProduto: "Bolsas",
      classificacaoProduto: "Mais_Vendidos2",
      exibirHome: true,
    },
    {
      codigoProduto: 9,
      tituloProduto: "Bolsa Bege Elegante",
      preco: 50000.00,
      descricao: "Bolsa Bege Elegante",
      imagemProduto: {
        img1: "./images/bolsa_9.png",
        img2: "./images/bolsa_9.png",
        img3: "./images/bolsa_9.png",
        img4: "./images/bolsa_9.png",
      },
      categoriaProduto: "Bolsas",
      classificacaoProduto: "Panter",
      exibirHome: true,
    },
    {
      codigoProduto: 10,
      tituloProduto: "Bolsa Verde Elegante",
      preco: 50000.00,
      descricao: "Bolsa Verde Elegante",
      imagemProduto: {
        img1: "./images/bolsa_principal.png",
        img2: "./images/bolsa_principal.png",
        img3: "./images/bolsa_principal.png",
        img4: "./images/bolsa_principal.png",
      },
      categoriaProduto: "Bolsas",
      classificacaoProduto: "Panter",
      exibirHome: true,
    },
    {
      codigoProduto: 11,
      tituloProduto: "Bolsa Vermelha Elegante",
      preco: 50000.00,
      descricao: "Bolsa Vermelha Elegante",
      imagemProduto: {
        img1: "./images/bolsa_principal_2.png",
        img2: "./images/bolsa_principal_2.png",
        img3: "./images/bolsa_principal_2.png",
        img4: "./images/bolsa_principal_2.png",
      },
      categoriaProduto: "Bolsas",
      classificacaoProduto: "Panter",
      exibirHome: true,
    },
    {
      codigoProduto: 12,
      tituloProduto: "Bolsa Preta Elegante",
      preco: 50000.00,
      descricao: "Bolsa Preta Elegante",
      imagemProduto: {
        img1: "./images/bolsa_principal_3.png",
        img2: "./images/bolsa_principal_3.png",
        img3: "./images/bolsa_principal_3.png",
        img4: "./images/bolsa_principal_3.png",
      },
      categoriaProduto: "Bolsas",
      classificacaoProduto: "Panter",
      exibirHome: true,
    },
  ];